### ISSUE TITLE
Current typescript types cannot describe custom grid

### ISSUE THREAD

**Issue by littleli** [santosfrancisco/react-awesome-styled-grid#71]
With custom grid you could have different amount of columns for example as described [here in the documentation](https://awesome-styled-grid.netlify.com/custom#using-a-custom-configuration). Types should be able somehow to describe it otherwise typescript builds with custom configuration fail.

**Comment by santosfrancisco** [comment]
@ixahmedxi Could you take a look at this issue?

**Comment by ixahmedxi** [comment]
Looking at this issue, the typescript types can’t be dynamic since the configuration can change and the .d.ts files can’t have the ability to read the change on my knowledge that’s why the only fix that I can see as of now is to rewrite the whole project in typescript which will eliminate the need of declaration files as that the types will already be in the code. Rewriting the project in typescript will also add a lot of neat features such as better debugging, finding potential bugs and many more. @santosfrancisco are you down for the idea?

**Comment by santosfrancisco** [comment]
@ixahmedxi, it's nice to have typescript support in lib, but I can't just rewrite in typescript since I won't be able to support it. So I prefer to remove Types until we have some solution for the custom grid. Sorry

**Comment by santosfrancisco** [comment]
@littleli , good night! I'm sorry for answering so late. This validation has been removed and you can now use types with the custom grid. Value validation removed and type validation remains
